export default {
  plugin: ['typedoc-plugin-markdown', 'typedoc-plugin-rename-defaults'],
  // Source.
  gitRevision: 'main',
  entryPoints: ['src/index.ts', 'src/typedoc.ts'],
  entryFileName: 'index.md',
  readme: 'none',
  cleanOutputDir: true,
  excludePrivate: true,
  excludeProtected: true,
  excludeInternal: true,
  // Output
  out: 'docs/api',
  // Order.
  groupOrder: [
    'Components – core',
    'Components – web objects',
    'Components – map sources',
    'Types (map provider)',
    'Types (web objects)',
    'Types (map sources)',
    'Map types',
    'Marker types',
    'Popup types',
    'Web object abstraction types',
    'Map source abstraction types',
    '*',
  ],
  sort: ['source-order'],
  sortEntryPoints: false,
  notRenderedTags: ['@sortStrategy', '@group', '@interface'],
  // Display.
  hidePageHeader: true,
  useCodeBlocks: false,
  expandObjects: true,
  expandParameters: true,
  indexFormat: 'table',
  parametersFormat: 'table',
  interfacePropertiesFormat: 'table',
  classPropertiesFormat: 'table',
  typeAliasPropertiesFormat: 'table',
  enumMembersFormat: 'table',
  propertyMembersFormat: 'table',
  typeDeclarationFormat: 'table',
  pageTitleTemplates: {
    member: '{name}',
  },
}
