export default {
  plugin: ['typedoc-plugin-markdown', 'typedoc-plugin-rename-defaults'],
  entryPoints: ['src/index.ts', 'src/typedoc.ts'],
  entryFileName: 'index.md',
  out: 'docs/api',
  readme: 'none',
  cleanOutputDir: true,
  excludePrivate: true,
  excludeProtected: true,
  excludeInternal: true,
  sort: ['source-order'],
  groupOrder: ['Components', 'Types', '*'],
  enumMembersFormat: 'table',
  parametersFormat: 'table',
  typeDeclarationFormat: 'table',
  indexFormat: 'table',
  useCodeBlocks: false,
  expandObjects: true,
  hideBreadcrumbs: false,
}
